baseURL = "https://sline.tech/"
languageCode = "en-us"
title = "Streamline"
theme = "SimpleIntro"

[params]
    mainbg = "https://drive.google.com/uc?export=view&id=1iXzjW2kCqMUG0c90aRurEstywNiDK8xF"
    name = "Streamline"
    mainTitle = "Streamline"
    mainText = "Ever wanted to go hands-free with your presentations?"